language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
      dist: xenial

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends texlive-full; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_wait 40 brew cask install mactex; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="$PATH:/Library/TeX/texbin"; fi

install:
  - pip install pytest pytest-cov coveralls
  - pip install .

before_cache:
  - brew cleanup

cache:
  ccache: true
  pip: true

script:
  - which pdflatex
  - which latexdiff
  - pytest --cov=comparxiv tests

after_success:
  - coveralls

notifications:
  email: true